Updated compile scripts for CI.

diff --git a/linux-lts-quantal-3.5.0/compile-debian b/linux-lts-quantal-3.5.0/compile-debian
--- a/linux-lts-quantal-3.5.0/compile-debian
+++ b/linux-lts-quantal-3.5.0/compile-debian
@@ -1,5 +1,8 @@
 #!/bin/bash
-set -e
+
+if [ ! -d debian ]; then
+	cp -r debian.theia debian
+fi
 
 fakeroot debian/rules clean
 
@@ -12,14 +15,18 @@ skipdbg=false \
 DEB_BUILD_OPTIONS=parallel=8 \
 NOEXTRAS=1 \
 CROSS_COMPILE=`pwd`/debian.master/bin/ \
-fakeroot debian/rules binary-generic V=1
+AUTOBUILD=1 \
+fakeroot debian/rules binary-generic binary-headers
 
-#skipabi=true \
-#AUTOBUILD=1 \
-#exit
+# The previous command sometimes fails on the first try
 
+if [[ $? -ne 0 ]]; then
 skipdbg=false \
 DEB_BUILD_OPTIONS=parallel=8 \
 NOEXTRAS=1 \
 CROSS_COMPILE=`pwd`/debian.master/bin/ \
-fakeroot debian/rules binary-headers V=1
+AUTOBUILD=1 \
+fakeroot debian/rules binary-generic binary-headers
+fi
+
+exit $?
