Apparently it's a bad idea to try to compile the generic binaries and headers at the same time...

diff --git a/linux-lts-quantal-3.5.0/compile-debian b/linux-lts-quantal-3.5.0/compile-debian
--- a/linux-lts-quantal-3.5.0/compile-debian
+++ b/linux-lts-quantal-3.5.0/compile-debian
@@ -15,7 +15,7 @@ DEB_BUILD_OPTIONS=parallel=8 \
 NOEXTRAS=1 \
 CROSS_COMPILE=`pwd`/debian.master/bin/ \
 AUTOBUILD=1 \
-fakeroot debian/rules binary-generic binary-headers
+fakeroot debian/rules binary-generic
 
 # The previous command sometimes fails on the first try
 
@@ -25,7 +25,31 @@ DEB_BUILD_OPTIONS=parallel=8 \
 NOEXTRAS=1 \
 CROSS_COMPILE=`pwd`/debian.master/bin/ \
 AUTOBUILD=1 \
-fakeroot debian/rules binary-generic binary-headers
+fakeroot debian/rules binary-generic
+fi
+
+# If it still fails, give up!
+
+if [[ $? -ne 0 ]]; then
+	exit $?
+fi
+
+skipdbg=false \
+DEB_BUILD_OPTIONS=parallel=8 \
+NOEXTRAS=1 \
+CROSS_COMPILE=`pwd`/debian.master/bin/ \
+AUTOBUILD=1 \
+fakeroot debian/rules binary-headers
+
+# The previous command sometimes fails on the first try
+
+if [[ $? -ne 0 ]]; then
+skipdbg=false \
+DEB_BUILD_OPTIONS=parallel=8 \
+NOEXTRAS=1 \
+CROSS_COMPILE=`pwd`/debian.master/bin/ \
+AUTOBUILD=1 \
+fakeroot debian/rules binary-headers
 fi
 
 exit $?
